"""Render the complete numerical report from the closed assessment analysis."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = {"memory": "Original memory", "original_predictive": "Original predictive seed",
         "predictive": "Selected generation 14", "frozen": "Selected, frozen weights",
         "no_planning": "Selected, fixed-risk", "frozen_no_planning": "Selected, frozen + fixed-risk"}


def number(value, digits=4):
    return "—" if value is None else f"{value:.{digits}f}"


def estimate(value, ci, scale=1., digits=4):
    if ci is None:
        return number(value, digits)
    return f"{number(value*scale, digits)} [{number(ci[0]*scale, digits)}, {number(ci[1]*scale, digits)}]"


def render(summary):
    lines = ["# Fresh assessment: complete numerical results", "",
        "Generated by `scripts/assessment_tables.py` from the closed "
        "[analysis](../artifacts/campaign-v2/assessment-1024/analysis.json). "
        "The manuscript interpretation is in the [README](../README.md).", "",
        "Exactly 1,024 paired cases and 6,144 condition-episodes. Brackets denote 95% intervals "
        "unless specified otherwise. Rates and binary differences are in percentage points. "
        "Binary paired intervals use the prespecified conservative exact-binomial construction; "
        "continuous and forecast intervals resample whole paired episodes 10,000 times. "
        "All recorded episodes, including invalid execution, remain in the denominators.", "",
        "## Per-condition outcomes", "",
        "| Condition | Escape | Death | Timeout | Door open | Both keys | Invalid |",
        "|---|---|---|---|---|---|---|"]
    for variant, name in NAMES.items():
        result = summary["agents"][variant]
        values = [f"{result[k]['count']}/1024; " + estimate(result[k]["rate"], result[k]["ci95"], 100, 2)
                  for k in ("escape", "death", "timeout", "door", "two_keys")]
        lines.append("| " + " | ".join([name, *values, str(result["invalid"])]) + " |")
    lines += ["", "Rate intervals are Wilson intervals. Invalid is a separate execution outcome; "
              "it is not relabelled as death or timeout.", "", "## Paired binary comparisons", "",
              "Left-only/right-only count presence of the named event. For death and timeout, "
              "right-only is the favorable win for the left agent; for escape, door and both keys, "
              "left-only is favorable. Differences are always left minus right event probability. "
              "All tests are two-sided exact McNemar. Only selected-minus-frozen escape is primary. "
              "The three secondary escape tests form a separate Holm family; other tests are exploratory."]
    comparisons = [(key, item["binary"]) for key, item in summary["contrasts"].items()]
    comparisons.append(("no_planning minus frozen_no_planning", summary["matched_prediction"]["binary"]))
    for name, metrics in comparisons:
        left, right = name.split(" minus ")
        lines += ["", f"### {NAMES[left]} minus {NAMES[right]}", "",
            "| Event | Left only | Right only | Both | Neither | Difference [95% CI] | Exact p | Holm p |",
            "|---|---:|---:|---:|---:|---|---:|---:|"]
        for event, result in metrics.items():
            lines.append(f"| {event} | {result['left_only']} | {result['right_only']} | "
                f"{result['both']} | {result['neither']} | "
                f"{estimate(result['difference'], result['ci95'], 100, 3)} | "
                f"{result['mcnemar_exact_p']:.6g} | "
                f"{format(result['holm_adjusted_p'], '.6g') if 'holm_adjusted_p' in result else '—'} |")
        escape = metrics["escape"]
        if "holm_adjusted_p" in escape:
            lines += ["", "Secondary simultaneous interval (Bonferroni, three contrasts): "
                + estimate(escape["difference"], escape["secondary_simultaneous_ci"], 100, 3) + "."]
        if name in summary["contrasts"]:
            cases = summary["contrasts"][name]["escape_discordances_involving_invalid"]
            lines += ["", f"Escape discordances involving invalid execution: {cases or 'none'}."]
    lines += ["", "## Task, prediction and efficiency", "",
              "| Condition | Keys | Task | Model score | Selection score | Episode steps |",
              "|---|---|---|---|---|---|"]
    for variant, name in NAMES.items():
        result = summary["agents"][variant]
        values = [estimate(result[k]["mean"], result[k]["ci95"]) for k in
                  ("keys", "task", "model_score", "combined_score", "steps")]
        lines.append("| " + " | ".join([name, *values]) + " |")
    lines += ["", "Episode steps include deaths, timeouts and invalid executions; fewer steps "
              "alone are not an unconditional benefit. The following escape means condition on "
              "each condition's own successes, which can be different cases.", "",
              "| Condition | Successful cases | Steps per success | Seconds per success | Seconds per episode | Median / p95 seconds | Total episode seconds |",
              "|---|---:|---|---|---|---|---:|"]
    for variant, name in NAMES.items():
        r = summary["agents"][variant]
        values = [estimate(r[k]["mean"], r[k]["ci95"], digits=3) for k in
                  ("successful_escape_steps", "successful_escape_seconds", "seconds")]
        lines.append("| " + " | ".join([name, str(r["escape"]["count"]), *values,
            f"{r['runtime_median_seconds']:.3f} / {r['runtime_p95_seconds']:.3f}",
            f"{r['runtime_total_seconds']:.2f}"]) + " |")
    lines += ["", "Host times include candidate startup, IPC, evaluation and temporary trace collection "
              "under four-case concurrency. Summed episode seconds are not experiment wall time.", "",
              "### On-policy forecast losses", "",
              "These pooled losses can reflect different trajectories and target distributions. "
              "They do not isolate parameter learning. Counts are scored cell-time targets.", "",
              "| Condition | Near loss [CI]; targets | Uniform-audit loss [CI]; targets | Threat loss [CI]; targets |",
              "|---|---|---|---|"]
    for variant, name in NAMES.items():
        r = summary["agents"][variant]
        values = [estimate(r[k]["value"], r[k]["ci95"], digits=6)+f"; {r[k]['targets']:,}"
                  for k in ("brier_near", "brier_audit", "brier_threat")]
        lines.append("| " + " | ".join([name, *values]) + " |")
    lines += ["", "### Paired continuous differences on each condition's own trajectory", "",
              "| Comparison | Metric | Left minus right [95% CI] |",
              "|---|---|---|"]
    for name, contrast in summary["contrasts"].items():
        for metric, result in {**contrast["continuous"], **contrast["on_policy_prediction"]}.items():
            if result:
                lines.append(f"| {name} | {metric} | {estimate(result['difference'], result['ci95'], digits=6)} |")
    matched = summary["matched_prediction"]
    lines += ["", "## Learning on verified fixed-risk experience", "",
              f"Trajectory and map/localization checks passed for every pair: **{matched['verified']}**. "
              f"Trajectory mismatches: {matched['trajectory_mismatch_cases']}; "
              f"map/localization mismatches: {matched['map_localization_mismatch_cases']}.", "",
              "| Forecast | Learned | Frozen | Difference [95% CI] | Relative loss reduction, % [95% CI] | Episodes | Targets per condition |",
              "|---|---:|---:|---|---|---:|---:|"]
    for metric, r in matched["metrics"].items():
        lines.append(f"| {metric} | {r['left_loss']:.6f} | {r['right_loss']:.6f} | "
            f"{estimate(r['difference'], r['ci95'], digits=6)} | "
            f"{estimate(r['relative_reduction'], r['relative_reduction_interval']['ci95'], 100, 3)} | "
            f"{r['left_episodes']} / {r['right_episodes']} | {r['left_targets']:,} / {r['right_targets']:,} |")
    lines += ["", "All bootstrap denominators and retained-draw counts are recorded in the JSON analysis. "
              "Relative reductions are ratios of pooled losses, not averages of episode ratios.", "",
              "### Matched near-loss time bins", "",
              "Intervals are pointwise, and later bins condition on surviving long enough to contribute.", "",
              "| Steps | Learned | Frozen | Difference [95% CI] | Episodes | Targets per condition |",
              "|---|---:|---:|---|---:|---:|"]
    for r in summary["learning_curve"]:
        lines.append(f"| {r['start_step']}–{r['end_step']} | {r['left_loss']:.6f} | "
            f"{r['right_loss']:.6f} | {estimate(r['difference'], r['ci95'], digits=6)} | "
            f"{r['left_episodes']} | {r['left_targets']:,} |")
    lines += ["", "## Intervention checks", "",
              "Parameter checks concern exported transition weights; the immutable original controls "
              "do not export this generation-14 parameter vector. Activity counts describe cases with "
              "a changed map or localized movement, rather than requiring activity after immediate termination.", "",
              "| Condition | Parameters exported | Constant | Changed | Map changed | Movement | Localization errors | Visible-map errors / checks |",
              "|---|---:|---:|---:|---:|---:|---:|---|"]
    for variant, name in NAMES.items():
        r = summary["interventions"][variant]
        values = [str(r[k]) for k in ("parameters_exported_cases", "parameters_constant_cases",
                  "parameters_changed_cases", "mapping_changed_cases", "localized_movement_cases", "localization_errors")]
        lines.append("| " + " | ".join([name, *values,
            f"{r['visible_terrain_errors']} / {r['visible_terrain_checks']:,}"]) + " |")
    lines += ["", "## Invalid executions", ""]
    lines.extend(f"- Case {r['case']:04d}, {NAMES[r['variant']]}: `{r['error']}`."
                 for r in summary["invalid_episodes"])
    if not summary["invalid_episodes"]:
        lines.append("None.")
    return "\n".join(lines)+"\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default="artifacts/campaign-v2/assessment-1024")
    parser.add_argument("--out", default="docs/assessment-results.md")
    args = parser.parse_args()
    path = Path(args.data)
    assert (path / "analysis-closed.json").exists(), "Close analysis before rendering results"
    summary = json.loads((path / "analysis.json").read_text())
    Path(args.out).write_text(render(summary))


if __name__ == "__main__":
    main()
